//
// Created by filipebafica on 07/09/23.
//

#ifndef WEB_SERVER_HTTPREQUESTPARSER_H
#define WEB_SERVER_HTTPREQUESTPARSER_H
#define SPACE_DELIMITER " "
#define COLONS_DELIMITER ":"
#define END_OF_LINE_DELIMITER "\r\n"
#define REQUEST_HEADER_START_INDEX 1
#define REQUEST_HEADER_PAIR_SIZE 2


#endif //WEB_SERVER_HTTPREQUESTPARSER_H
